spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql

  jpa:
    generate-ddl: true

#  hibernate:
#    ddl-auto: validate
#
#  properties:
#    hibernate:
#    format_sql: true
#
#  show-sql: true