CREATE TABLE IF NOT EXISTS animals
(
    id   SERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS continents
(
    id   SERIAL PRIMARY KEY,
    area VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS populations
(
    id   SERIAL PRIMARY KEY,
    number BIGINT NOT NULL
);

